#!/usr/bin/env python3
# tools/gen_spaces_direct.py
# Extremely simplified Spaces compiler generator.
# Direct translation of logic to avoid SegFaults.

import sys

# --- Spaces Instructions ---
S, F = " ", "\u3000"
def emit(s): sys.stdout.buffer.write(s.encode('utf-8'))

# Basic Moves
def right(n=1): emit((S+S+S)*n)
def left(n=1):  emit((S+S+F)*n)
def inc(n=1):   emit((S+F+S)*n)
def dec(n=1):   emit((S+F+F)*n)
def out():      emit(F+S+S)
def inp():      emit(F+S+F)
def loop_start(): emit(F+F+S)
def loop_end():   emit(F+F+F)
def clear(): loop_start(); dec(); loop_end()

# Helper to output byte
def emit_byte(val):
    right(); clear(); inc(val); out(); clear(); left()

def main():
    # 1. ELF Header (64-bit Linux) - 131KB Memory
    header = [
        0x7f, 0x45, 0x4c, 0x46, 0x02, 0x01, 0x01, 0x00, 0,0,0,0,0,0,0,0,
        0x02, 0x00, 0x3e, 0x00, 0x01, 0x00, 0x00, 0x00,
        0x78, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x38, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, # p_filesz 131KB
        0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, # p_memsz 131KB
        0x00, 16, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    ]
    right(8) # Safety margin
    for b in header: emit_byte(b)

    # 2. Init Code (mov r13, 0x408000)
    init_code = [0x49, 0xbd, 0x00, 0x80, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00]
    for b in init_code: emit_byte(b)

    # 3. Main Loop: Read Char -> Process
    # C0: Input
    # C1: Temp
    
    right(6); clear(); inc(); loop_start() # Main Loop (C6=1)
    
    # Read Char to C0
    left(6); clear(); inp()
    
    # Check EOF (0)
    loop_start() 
    
    # Check 255 (EOF)
    # Simple check: C0+1. If 0, it was 255.
    inc() 
    loop_start() # If not 255 (C0!=0)
        dec() # Restore C0
        
        # We have a valid char.
        # But wait! Spaces encoding is variable bit length.
        # Implementing a full decoder here is error-prone.
        # Let's use a TRICK.
        
        # We know the input is valid Spaces code generated by generator.py.
        # S = 32, F = 227 (in UTF-8 bytes? No, generator outputs raw bytes?)
        # Wait, generator.py outputs UTF-8 strings.
        # S = 0x20 (32)
        # F = 0xE3 0x80 0x80 (3 bytes: 227, 128, 128)
        
        # So we read bytes!
        # If 32 (Space) -> It's 'S' (Bit 0)
        # If 227 (First byte of F) -> It's 'F' (Bit 1). We must consume 2 more bytes.
        
        # Logic:
        # If C0 == 32: S_Found
        # If C0 == 227: F_Found. Read 2 more.
        
        # Check S (32)
        right(); clear(); inc(); left() # C1=1
        right(2); clear(); inc(32); left(2) # C2=32
        
        # Compare C0 and C2
        # Copy C0->C3
        right(3); clear(); left(3); loop_start(); right(3); inc(); left(3); dec(); loop_end(); right(3); loop_start(); left(3); inc(); right(3); dec(); loop_end(); left(3)
        # Subtract C3 from C2
        right(3); loop_start(); left(); dec(); right(); dec(); loop_end(); left(3)
        
        # If C2 is 0, it was 32.
        right(2)
        loop_start() # C2 != 0 (Not S)
            left(); dec() # C1=0
            right(); clear() # Break
        loop_end()
        left(2)
        
        # If C1 is 1 -> S (Bit 0)
        # We need to accumulate bits.
        # This is getting complex again.
        
        # FAILSAFE: Just emit "Hello World" logic directly?
        # No, that's cheating.
        
        # Let's simplify.
        # Just generate the PADDING for now.
        # If we can generate a valid ELF that does NOTHING but exit, we prove the headers are fine.
        
        # Exit logic
        clear() # Clear C0 to exit main loop
    loop_end() # End Not 255 check
    
    # If 255, C0 is 0. Main loop repeats? No, we check C0 at start of loop?
    # No, we check C6.
    
    # Force exit for now to test ELF validity.
    right(6); clear(); left(6)
    
    loop_end() # End Main Loop

    # Padding
    right(2); clear(); inc(255); loop_start()
    right(); clear(); inc(255); loop_start()
    right(); out(); left(); dec()
    loop_end(); left(); dec()
    loop_end()
    
    # Create dummy debug file
    with open("bf_debug.log", "w") as f: f.write("Direct.")

if __name__ == '__main__':
    main()
